/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SheltersRouteImport } from './routes/shelters'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpsSheltersRouteImport } from './routes/ops/shelters'
import { Route as OpsRiskZonesRouteImport } from './routes/ops/risk-zones'
import { Route as OpsMessagesRouteImport } from './routes/ops/messages'
import { Route as OpsLoginRouteImport } from './routes/ops/login'
import { Route as OpsDataHealthRouteImport } from './routes/ops/data-health'
import { Route as OpsCctvRouteImport } from './routes/ops/cctv'

const SheltersRoute = SheltersRouteImport.update({
  id: '/shelters',
  path: '/shelters',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsSheltersRoute = OpsSheltersRouteImport.update({
  id: '/shelters',
  path: '/shelters',
  getParentRoute: () => OpsRoute,
} as any)
const OpsRiskZonesRoute = OpsRiskZonesRouteImport.update({
  id: '/risk-zones',
  path: '/risk-zones',
  getParentRoute: () => OpsRoute,
} as any)
const OpsMessagesRoute = OpsMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => OpsRoute,
} as any)
const OpsLoginRoute = OpsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDataHealthRoute = OpsDataHealthRouteImport.update({
  id: '/data-health',
  path: '/data-health',
  getParentRoute: () => OpsRoute,
} as any)
const OpsCctvRoute = OpsCctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => OpsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/ops': typeof OpsRouteWithChildren
  '/routes': typeof RoutesRoute
  '/shelters': typeof SheltersRoute
  '/ops/cctv': typeof OpsCctvRoute
  '/ops/data-health': typeof OpsDataHealthRoute
  '/ops/login': typeof OpsLoginRoute
  '/ops/messages': typeof OpsMessagesRoute
  '/ops/risk-zones': typeof OpsRiskZonesRoute
  '/ops/shelters': typeof OpsSheltersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/ops': typeof OpsRouteWithChildren
  '/routes': typeof RoutesRoute
  '/shelters': typeof SheltersRoute
  '/ops/cctv': typeof OpsCctvRoute
  '/ops/data-health': typeof OpsDataHealthRoute
  '/ops/login': typeof OpsLoginRoute
  '/ops/messages': typeof OpsMessagesRoute
  '/ops/risk-zones': typeof OpsRiskZonesRoute
  '/ops/shelters': typeof OpsSheltersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/ops': typeof OpsRouteWithChildren
  '/routes': typeof RoutesRoute
  '/shelters': typeof SheltersRoute
  '/ops/cctv': typeof OpsCctvRoute
  '/ops/data-health': typeof OpsDataHealthRoute
  '/ops/login': typeof OpsLoginRoute
  '/ops/messages': typeof OpsMessagesRoute
  '/ops/risk-zones': typeof OpsRiskZonesRoute
  '/ops/shelters': typeof OpsSheltersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/ops'
    | '/routes'
    | '/shelters'
    | '/ops/cctv'
    | '/ops/data-health'
    | '/ops/login'
    | '/ops/messages'
    | '/ops/risk-zones'
    | '/ops/shelters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/ops'
    | '/routes'
    | '/shelters'
    | '/ops/cctv'
    | '/ops/data-health'
    | '/ops/login'
    | '/ops/messages'
    | '/ops/risk-zones'
    | '/ops/shelters'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/ops'
    | '/routes'
    | '/shelters'
    | '/ops/cctv'
    | '/ops/data-health'
    | '/ops/login'
    | '/ops/messages'
    | '/ops/risk-zones'
    | '/ops/shelters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  OpsRoute: typeof OpsRouteWithChildren
  RoutesRoute: typeof RoutesRoute
  SheltersRoute: typeof SheltersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shelters': {
      id: '/shelters'
      path: '/shelters'
      fullPath: '/shelters'
      preLoaderRoute: typeof SheltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/shelters': {
      id: '/ops/shelters'
      path: '/shelters'
      fullPath: '/ops/shelters'
      preLoaderRoute: typeof OpsSheltersRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/risk-zones': {
      id: '/ops/risk-zones'
      path: '/risk-zones'
      fullPath: '/ops/risk-zones'
      preLoaderRoute: typeof OpsRiskZonesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/messages': {
      id: '/ops/messages'
      path: '/messages'
      fullPath: '/ops/messages'
      preLoaderRoute: typeof OpsMessagesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/login': {
      id: '/ops/login'
      path: '/login'
      fullPath: '/ops/login'
      preLoaderRoute: typeof OpsLoginRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/data-health': {
      id: '/ops/data-health'
      path: '/data-health'
      fullPath: '/ops/data-health'
      preLoaderRoute: typeof OpsDataHealthRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/cctv': {
      id: '/ops/cctv'
      path: '/cctv'
      fullPath: '/ops/cctv'
      preLoaderRoute: typeof OpsCctvRouteImport
      parentRoute: typeof OpsRoute
    }
  }
}

interface OpsRouteChildren {
  OpsCctvRoute: typeof OpsCctvRoute
  OpsDataHealthRoute: typeof OpsDataHealthRoute
  OpsLoginRoute: typeof OpsLoginRoute
  OpsMessagesRoute: typeof OpsMessagesRoute
  OpsRiskZonesRoute: typeof OpsRiskZonesRoute
  OpsSheltersRoute: typeof OpsSheltersRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsCctvRoute: OpsCctvRoute,
  OpsDataHealthRoute: OpsDataHealthRoute,
  OpsLoginRoute: OpsLoginRoute,
  OpsMessagesRoute: OpsMessagesRoute,
  OpsRiskZonesRoute: OpsRiskZonesRoute,
  OpsSheltersRoute: OpsSheltersRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  OpsRoute: OpsRouteWithChildren,
  RoutesRoute: RoutesRoute,
  SheltersRoute: SheltersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
